<div data-bind="scope: myvendor-helloworld">
    <h2 data-bind="text: title"></h2>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "myvendor-helloworld": {
                        "component": "MyVendor_HelloWorld/js/component",
                        "title": "Hello World from UiComponents !",
                    }
                }
            }
        }
    }
</script>
