<?php
    /**
     * @var MyVendor\HelloWorld\Block\CustomBlock $block
     */
?>

<link
    rel="stylesheet"
    type="text/css"
    href="<?php echo $block->getViewFileUrl("MyVendor_HelloWorld::css/customBlockStyle.css") ?>" />

<h1>
    <?php echo $block->helloWorld() ?>
</h1>

<span id="loucura">
    <div data-bind="scope: 'helloworld_uicomponent' " id="template_html_component">
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
    </div>
</span>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
